import dynamic from 'next/dynamic';

const UI = dynamic(() => import('./realUi'))

export default UI


// import type { NextPage } from 'next'
// import Head from 'next/head'

// // import Layout from '../components/layout/Layout'
// import Counter from '../components/Counter'
// import Title from '../components/Title'
// // import useStore from '../lib/store'
// import useStore from 'ui/store'
// // const Layout = (await import('../components/layout/Layout')).default
// const Layout = dynamic(() => import('ui/Layout'))
// // const Counter = (await import('../components/Counter')).default
// // const Title = (await import('../components/Title')).default
// // const useStore = (await import('../lib/store')).default

// const UI: NextPage = () => {

//   const { count, increment, decrement } = useStore();

//   return (
//     <>
//       <Head>
//         <title>UI</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <Layout>
//           <Title text="UI" />
//           <Counter count={count} onIncrement={increment} onDecrement={decrement} />
//         </Layout>
//       </main>
//     </>
//   )
// }

// UI.getInitialProps = async () => {
//   return {};
// }

// export default UI
