import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'
import theme from '../theme'

const Layout = dynamic(() => import('ui/Layout'));
// const Counter = dynamic(() => import('ui/Counter'));
import useStore from 'ui/store';
import Counter from 'ui/Counter';
import Title from 'ui/Title';

const UI: NextPage = () => {

  const { count, increment, decrement } = useStore();

  return (
    <>
      <Head>
        <title>UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Title text="UI" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  )
}

UI.getInitialProps = async (ctx) => {
  return {};
}

export default UI
