import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'

import Layout from 'ui/Layout';
// const Layout = dynamic(async () => (await import('ui/Layout')));
import useStore, { InitialState } from 'ui/store';
import Counter from 'ui/Counter';
import Title from 'ui/Title';

const UI = () => {

  const { count, increment } = useStore();
  const decrement = useStore((state: InitialState) => state.decrement)

  return (
    <>
      <Head>
        <title>UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Title text="UI" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  )
}

// UI.getInitialProps = async (ctx) => {
//   return {};
// }

export default UI
