import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'

const Layout = dynamic(() => import('ui/Layout'));
const Counter = dynamic(() => import('ui/Counter'));
const Title = dynamic(() => import('ui/Title'));

import useStore from 'ui/store'

function Home(data: any) {

  const { count, increment, decrement } = useStore();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Title text="Home" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
          {/* <div>
            <h3>Data:</h3>
            {JSON.stringify(data)}
          </div> */}
        </Layout>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const data = await fetch('https://jsonplaceholder.typicode.com/todos/2').then(res => res.json());
  return data;
}

export default Home
