import Head from 'next/head'
import getTodos from '../lib/api'

import Layout from 'ui/Layout'
import Counter from 'ui/Counter'
import Title from 'ui/Title'
import useStore from 'ui/store'

interface PostData {
  postData: any
}

function Home({postData}: PostData) {
  console.log("postData ::", postData)

  const { count, increment, decrement } = useStore()

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Title text="Home" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
          <div>
            <h3>Data:</h3>
            {JSON.stringify(postData)}
          </div>
        </Layout>
      </main>
    </>
  )
}

Home.getInitialProps = async () => {
  const postData: PostData = await getTodos()
  return { postData };
}


// export const getServerSideProps: GetServerSideProps = async (context) => {
//   console.log("getServerSideProps", context)
//   const response = await fetch("https://jsonplaceholder.typicode.com/todos/1");
//   const postData = await response.json();
//   if (!postData) {
//     return {
//       notFound: true,
//     }
//   }
//   return {
//     props: {postData}
//   };
// }

export default Home