import { NextPage } from 'next'
import Head from 'next/head'
import getTodos from '../lib/api'
import dynamic from 'next/dynamic';

const Layout = (await import('ui/Layout')).default
// const Layout = dynamic(() => import('ui/Layout'))
const Counter = (await import('ui/Counter')).default
// const Nav = (await import('ui/Nav')).default
import Nav from '../components/Nav'
// const Nav = dynamic(() => import('ui/Nav'))
// const Title = dynamic(() => import('ui/Title'))
const Title = (await import('ui/Title')).default
const useStore = (await import('ui/store')).default

interface PostData {
  postData: any
}

// const Nav = (await import('ui/Nav')).default
const RealHome: NextPage = () => {
  // console.log("postData ::", postData)

  const { count, increment, decrement } = useStore()

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Layout>
          <Title text="Home" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
          <div>
            <h3>Data:</h3>
            {/* {JSON.stringify(postData)} */}
          </div>
        </Layout>
      </main>
    </>
  )
}

RealHome.getInitialProps = async (ctx) => {
  // const postData = fetch('https://jsonplaceholder.typicode.com/todos/5').then(res => res.json());
  // const Nav = dynamic(() => import('ui/Nav'))

  // const data = { postData, Nav }
  return { ctx };
}

export default RealHome