import { NextPage } from 'next'
import Head from 'next/head'
import getTodos from '../lib/api'
import dynamic from 'next/dynamic';

const Layout = (await import('ui/Layout')).default
const Counter = (await import('ui/Counter')).default
const Title = (await import('ui/Title')).default
const useStore = (await import('ui/store')).default

interface PostData {
  postData: any
}

const RealHome = ({ postData }: PostData) => {
  console.log("postData ::", postData)

  const { count, increment, decrement } = useStore()

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Title text="Home" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
          <div>
            <h3>Data:</h3>
            {JSON.stringify(postData)}
          </div>
        </Layout>
      </main>
    </>
  )
}

RealHome.getInitialProps = async () => {
  const postData: PostData = await getTodos()
  return { props: postData };
}

export default RealHome