
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const useStore = (await import('../fed-store/uiStore')).default
const Nav = dynamic(() => import('../fed-components/uiNav'))
const Layout = dynamic(() => import('../fed-components/uiLayout'))
const Title = dynamic(() => import('../fed-components/uiTitle'))
const Counter = dynamic(() => import('../fed-components/uiCounter'))

const RealProducts: NextPage = () => {

  const { count, increment, decrement } = useStore();

  return (
    <>
      <Head>
        <title>RealProducts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Layout>
          <Title text="RealProducts" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  )
}

RealProducts.getInitialProps = async (ctx) => {
  return { ctx };
}

export default RealProducts