import { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'

import getTodos from '../lib/api';

// Federated imports
const useStore = (await import('../fed-store/uiStore')).default
const Nav = dynamic(() => import('../fed-components/uiNav'))
const Title = dynamic(() => import('../fed-components/uiTitle'))
const Counter = dynamic(() => import('../fed-components/uiCounter'))

const RealHome: NextPage = () => {

  const { count, increment, decrement } = useStore()
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Title text="Home" />
        <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        <div>
          <h3>Data:</h3>
        </div>
      </main>
    </>
  )
}

RealHome.getInitialProps = async (ctx) => {
  const data = getTodos
  return { ctx };
}

export default RealHome