import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Nav from '../components/Nav'

// const Layout = (await import('ui/Layout')).default

const RealServer: NextPage = () => {

  return (
    <>
      <Head>
        <title>RealServer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {/* <Layout> */}
          <h1>
            RealServer
          </h1>
          <br />
          <Link href="/" >
            <a>Home</a>
          </Link>
          <Link href="/login" >
            <a>Login</a>
          </Link>
          <Link href="/ui" >
            <a>UI</a>
          </Link>
        {/* </Layout> */}
      </main>
    </>
  )
}

RealServer.getInitialProps = async (ctx) => {
  return {ctx};
}

export default RealServer
