import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
// import Nav from 'ui/Nav'

// const Layout = (await import('ui/Layout')).default
const Nav = (await import('ui/Nav')).default

const RealServer: NextPage = () => {

  return (
    <>
      <Head>
        <title>RealServer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {/* <Layout> */}
          <h1>
            RealServer
          </h1>
          <br />
        {/* </Layout> */}
      </main>
    </>
  )
}

RealServer.getInitialProps = async (ctx) => {
  return {ctx};
}

export default RealServer
