import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Layout = (await import('ui/Layout')).default

const RealServer: NextPage = () => {

  return (
    <>
      <Head>
        <title>Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <h1>
            Server
          </h1>
          <br />
          <Link href="/" >
            <a>Home</a>
          </Link>
          <Link href="/login" >
            <a>Login</a>
          </Link>
          <Link href="/ui" >
            <a>UI</a>
          </Link>
        </Layout>
      </main>
    </>
  )
}

// Server.getInitialProps = async (ctx) => {
//   return {};
// }

export default RealServer
