import dynamic from 'next/dynamic';

import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from "../components/Nav";

import Layout from '../components/layout/Layout'
import Counter from '../components/Counter'
import Title from '../components/Title'
import useStore from '../lib/store'

const RealUI: NextPage = () => {

  const { count, increment, decrement } = useStore();

  return (
    <>
      <Head>
        <title>RealUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {/* <Layout> */}
          <Title text="RealUI" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        {/* </Layout> */}
      </main>
    </>
  )
}

RealUI.getInitialProps = async (ctx) => {
  return { ctx };
}

export default RealUI
